export const STUDENT_SUBS = 'STUDENT_SUBS';
export const STUDENT_IS_PART = 'STUDENT_IS_PART';
export const STUDENT_NOT_PART = 'STUDENT_NOT_PART';
export const STUDENT_WAS_PART = 'STUDENT_NOT_PART';
export const ERROR_IN_STUDENT_AUTH = 'ERROR_IN_STUDENT_AUTH';

export const ASSEMBLY_NOT_AVABILE = 'ASSEMBLY_NOT_AVABILE';
export const ASSEMBLY_SUBS_CLOSE = 'ASSEMBLY_SUBS_CLOSE';
export const ASSEMBLY_SUBS_OPEN = 'ASSEMBLY_SUBS_OPEN';
export const ASSEMBLY_ERROR = 'ASSEMBLY_ERROR';