/**
 * STUDENT
 */
export const STUDENT_SUBS = 'STUDENT_SUBS';
export const STUDENT_IS_PART = 'STUDENT_IS_PART';
export const STUDENT_NOT_PART = 'STUDENT_NOT_PART';
export const STUDENT_WAS_PART = 'STUDENT_WAS_PART';
export const STUDENT_SUBED = 'STUDENT_SUBED';
export const UPDATE_STUDENT_LABS = 'UPDATE_STUDENT_LABS';
export const FETCH_STUDENT_LABS = 'FETCH_STUDENT_LABS';
export const ERROR_IN_STUDENT_AUTH = 'ERROR_IN_STUDENT_AUTH';
export const ERROR_IN_STUDENT_LABS_UPDATE = 'ERROR_IN_STUDENT_LABS_UPDATE';
export const ERROR_IN_STUDENT_LABS_FETCH = 'ERROR_IN_STUDENT_LABS_FETCH'
export const FETCH_STUDENT_PENDING = 'FETCH_STUDENT_PENDING';


/**
 * ASSEMBLY
 */
// Fetch info
export const FETCH_ASSEMBLY_INFO = 'FETCH_ASSEMBLY_INFO';
export const ASSEMBLY_SUBS_CLOSE = 'ASSEMBLY_SUBS_CLOSE';
export const ASSEMBLY_SUBS_OPEN = 'ASSEMBLY_SUBS_OPEN';
export const ASSEMBLY_NOT_AVABILE = 'ASSEMBLY_NOT_AVABILE';
export const ERROR_IN_ASSEMBLY_FETCH = 'ERROR_IN_ASSEMBLY_FETCH';
// Fetch laboratories
export const FETCH_ASSEMBLY_LABS = 'FETCH_ASSEMBLY_LABS';
export const ASSEMBLY_LABS_FETCHED = 'ASSEMBLY_LABS_FETCHED';
export const ERROR_IN_LABS_FETCH = 'ERROR_IN_LABS_FETCH';
// Update info
export const UPDATE_ASSEMBLY_INFO = 'UPDATE_ASSEMBLY_INFO';
export const ASSEMBLY_INFO_UPDATED = 'ASSEMBLY_INFO_UPDATED';
export const ERROR_IN_ASSEMBLY_INFO_UPDATE = 'ERROR_IN_ASSEMBLY_INFO_UPDATE';
// Create laboratory
export const CREATE_ASSEMBLY_LAB = 'CREATE_ASSEMBLY_LAB';
export const ASSEMBLY_LAB_CREATED = 'ASSEMBLY_LAB_CREATED';
export const ERROR_IN_ASSEMBLY_LAB_CREATE = 'ERROR_IN_ASSEMBLY_LAB_CREATE';
// Update laboratory
export const UPDATE_ASSEMBLY_LAB = 'UPDATE_ASSEMBLY_LAB';
export const ASSEMBLY_LAB_UPDATED = 'ASSEMBLY_LAB_UPDATED';
export const ERROR_IN_ASSEMBLY_LAB_UPDATE = 'ERROR_IN_ASSEMBLY_LAB_UPDATE';
// Delete laboratory
export const DELETE_ASSEMBLY_LAB = 'CREATE_ASSEMBLY_LAB';
export const ASSEMBLY_LAB_DELETED = 'ASSEMBLY_LAB_CREATED';
export const ERROR_IN_ASSEMBLY_LAB_DELETE = 'ERROR_IN_ASSEMBLY_LAB_CREATE';
// Fetch students
export const FETCH_ASSEMBLY_STUDENTS = 'FETCH_ASSEMBLY_STUDENTS';
export const ASSEMBLY_STUDENTS_FETCHED = 'ASSEMBLY_STUDENTS_FETCHED';
export const ERROR_IN_STUDENTS_FETCH = 'ERROR_IN_STUDENTS_FETCH';
//Delete assembly
export const DELETE_ASSEMBLY = 'DELETE_ASSEMBLY';
export const ASSEMBLY_DELETED = 'ASSEMBLY_DELETED';
export const ERROR_IN_ASSEMBLY_DELETE = 'ERROR_IN_ASSEMBLY_DELETE';
// General
export const FETCH_ASSEMBLY_PENDING = 'FETCH_ASSEMBLY_PENDING';
export const FETCH_ASSEMBLY_DONE = 'FETCH_ASSEMBLY_DONE';


/**
 * ADMIN
 */
export const AUTH_ADMIN_PENDING = 'AUTH_ADMIN_PENDING';
export const ADMIN_AUTHED = 'ADMIN_AUTHED';
export const ERROR_IN_ADMIN_AUTH = 'ERROR_IN_ADMIN_AUTH';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';