/**
 * STUDENT
 */
export const STUDENT_SUBS = 'STUDENT_SUBS';
export const STUDENT_IS_PART = 'STUDENT_IS_PART';
export const STUDENT_NOT_PART = 'STUDENT_NOT_PART';
export const STUDENT_SUBED = 'STUDENT_SUBED';
export const STUDENT_FETCH_PENDING = 'STUDENT_FETCH_PENDING';
export const STUDENT_LABS_FETCHED = 'STUDENT_LABS_FETCHED';
export const STUDENT_FETCH_ERROR = 'STUDENT_FETCH_ERROR';
export const STUDENT_LOGOUT = 'STUDENT_LOGOUT';
export const UPDATE_STUDENT_TOKEN = 'UPDATE_STUDENT_TOKEN';

/**
 * ASSEMBLY
 */
// Fetch assembly
export const ASSEMBLY_FETCH_PENDING = 'ASSEMBLY_FETCH_PENDING';
export const ASSEMBLY_FETCHED = 'ASSEMBLY_FETCHED';
export const ASSEMBLY_INFO_FETCH_ERROR = 'ASSEMBLY_INFO_FETCH_ERROR';
// Backup assembly
export const ASSEMBLY_FETCH_ERROR = 'ASSEMBLY_FETCH_ERROR';
// Load assembly
export const ASSEMBLY_LOAD_COMPLETED = 'ASSEMBLY_LOAD_COMPLETED';
// Delete assembly
export const ASSEMBLY_DELETED = 'ASSEMBLY_DELETED';
// Fetch info
export const ASSEMBLY_SUBS_CLOSE = 'ASSEMBLY_SUBS_CLOSE';
export const ASSEMBLY_SUBS_OPEN = 'ASSEMBLY_SUBS_OPEN';
export const ASSEMBLY_NOT_AVABILE = 'ASSEMBLY_NOT_AVABILE';
// Update info
export const ASSEMBLY_INFO_UPDATED = 'ASSEMBLY_INFO_UPDATED';
// Update labs
export const ASSEMBLY_LABS_MUTATION = 'ASSEMBLY_LABS_MUTATION';
// Fetch students
export const STUDENTS_FETCHED = 'STUDENTS_FETCHED';
// Generate pdf
export const ASSEMBLY_PDF_COMPLETED = 'ASSEMBLY_PDF_COMPLETED';
export const CLEAR_ASSEMBLY_MESSAGE = 'CLEAR_ASSEMBLY_MESSAGE';
export const DISPLAY_ASSEMBLY_MESSAGE = 'DISPLAY_ASSEMBLY_MESSAGE';

/**
 * ADMIN
 */
export const ADMIN_FETCH_PENDING = 'ADMIN_FETCH_PENDING';
export const ADMIN_AUTHED = 'ADMIN_AUTHED';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
export const UPDATE_ADMIN_TOKEN = 'UPDATE_ADMIN_TOKEN';
export const SUDOER_AUTHED = 'SUDOER_AUTHED';
export const ADMIN_FETCH_ERROR = 'ADMIN_FETCH_ERROR';

/**
 * PREFERENCE
 */
export const SWITCH_THEME = 'SWITCH_THEME';
